# scripts/back_translate.py
"""
Back-translation data augmentation for MSLG-SPA 2026.

Pipeline:
  1. Load external Spanish sentences
  2. Translate SPA → MSLG using trained SPA2MSLG model
  3. Filter synthetic pairs by round-trip consistency
  4. Save augmented dataset

Usage:
    python scripts/back_translate.py \
        --config configs/baseline.yaml \
        --spa_file data/raw/external_spanish.txt \
        --output data/processed/augmented_train.tsv \
        --round_trip_threshold 0.4

Round-trip filtering:
    SPA → SPA2MSLG → synthetic MSLG → MSLG2SPA → reconstructed SPA
    Keep pair if chrF(original SPA, reconstructed SPA) > threshold
"""

import argparse
import yaml
import pandas as pd
from pathlib import Path
from tqdm import tqdm

from src.data.dataset import load_pairs
from src.evaluation.metrics import compute_chrf
from scripts.run_evaluate import load_trained_model, generate_translations


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config",                required=True)
    parser.add_argument("--spa_file",              required=True,
                        help="Plain text file with one Spanish sentence per line")
    parser.add_argument("--output",                required=True,
                        help="Output TSV file for augmented training data")
    parser.add_argument("--mslg2spa_checkpoint",   required=True,
                        help="Path to trained MSLG2SPA model checkpoint")
    parser.add_argument("--spa2mslg_checkpoint",   required=True,
                        help="Path to trained SPA2MSLG model checkpoint")
    parser.add_argument("--round_trip_threshold",  type=float, default=0.4,
                        help="Minimum chrF score for round-trip filter (0-1)")
    parser.add_argument("--max_sentences",         type=int, default=500,
                        help="Maximum number of external sentences to process")
    return parser.parse_args()


def load_config(path: str) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def load_external_spanish(filepath: str, max_sentences: int) -> list[str]:
    """
    Load external Spanish sentences from a plain text file.
    One sentence per line.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        sentences = [line.strip() for line in f if line.strip()]
    sentences = sentences[:max_sentences]
    print(f"Loaded {len(sentences)} external Spanish sentences")
    return sentences


def round_trip_filter(
    spa_originals: list[str],
    synthetic_glosses: list[str],
    mslg2spa_model,
    mslg2spa_tokenizer,
    threshold: float,
    max_src_len: int,
    max_new_tokens: int,
    num_beams: int,
) -> list[tuple[str, str]]:
    """
    Filter synthetic pairs by round-trip consistency.

    For each (spa_original, synthetic_gloss) pair:
      1. Translate synthetic_gloss back to Spanish using MSLG2SPA
      2. Compute chrF between spa_original and reconstructed Spanish
      3. Keep pair only if chrF > threshold

    Args:
        spa_originals:      Original Spanish sentences
        synthetic_glosses:  Synthetic MSL glosses generated by SPA2MSLG
        mslg2spa_model:     Trained MSLG2SPA model
        mslg2spa_tokenizer: Corresponding tokenizer
        threshold:          Minimum chrF score to keep a pair
        max_src_len:        Max tokenization length
        max_new_tokens:     Max generation length
        num_beams:          Beam search width

    Returns:
        List of (mslg, spa) pairs that passed the filter
    """
    print("Running round-trip filter...")

    # Translate synthetic glosses back to Spanish
    reconstructed_spa = generate_translations(
        model=mslg2spa_model,
        tokenizer=mslg2spa_tokenizer,
        sources=synthetic_glosses,
        max_src_len=max_src_len,
        max_new_tokens=max_new_tokens,
        num_beams=num_beams,
    )

    # Filter by chrF between original and reconstructed Spanish
    kept_pairs = []
    filtered_count = 0

    for orig, gloss, recon in zip(spa_originals, synthetic_glosses, reconstructed_spa):
        # Compute chrF as a similarity score (normalize to 0-1)
        score = compute_chrf([recon], [orig]) / 100.0

        if score >= threshold:
            kept_pairs.append((gloss, orig))
        else:
            filtered_count += 1

    print(f"Round-trip filter: kept {len(kept_pairs)}, "
          f"filtered {filtered_count} "
          f"(threshold={threshold})")

    return kept_pairs


def main():
    args   = parse_args()
    config = load_config(args.config)

    max_src_len   = config["model"]["max_source_length"]
    max_new_tokens = config["generation"]["max_new_tokens"]
    num_beams     = config["generation"]["num_beams"]

    # ------------------------------------------------------------------ #
    # 1. Load external Spanish sentences
    # ------------------------------------------------------------------ #
    spa_sentences = load_external_spanish(args.spa_file, args.max_sentences)

    # ------------------------------------------------------------------ #
    # 2. Load SPA2MSLG model
    # ------------------------------------------------------------------ #
    print("Loading SPA2MSLG model...")
    spa2mslg_model, spa2mslg_tokenizer = load_trained_model(args.spa2mslg_checkpoint)

    # ------------------------------------------------------------------ #
    # 3. Generate synthetic MSL glosses
    # ------------------------------------------------------------------ #
    print("Generating synthetic MSL glosses...")
    synthetic_glosses = generate_translations(
        model=spa2mslg_model,
        tokenizer=spa2mslg_tokenizer,
        sources=spa_sentences,
        max_src_len=max_src_len,
        max_new_tokens=max_new_tokens,
        num_beams=num_beams,
    )

    print(f"Generated {len(synthetic_glosses)} synthetic glosses")
    print("\nExamples:")
    for spa, gloss in zip(spa_sentences[:5], synthetic_glosses[:5]):
        print(f"  SPA:  {spa}")
        print(f"  MSLG: {gloss}")
        print()

    # ------------------------------------------------------------------ #
    # 4. Round-trip filter
    # ------------------------------------------------------------------ #
    print("Loading MSLG2SPA model for round-trip filter...")
    mslg2spa_model, mslg2spa_tokenizer = load_trained_model(args.mslg2spa_checkpoint)

    kept_pairs = round_trip_filter(
        spa_originals=spa_sentences,
        synthetic_glosses=synthetic_glosses,
        mslg2spa_model=mslg2spa_model,
        mslg2spa_tokenizer=mslg2spa_tokenizer,
        threshold=args.round_trip_threshold,
        max_src_len=max_src_len,
        max_new_tokens=max_new_tokens,
        num_beams=num_beams,
    )

    # ------------------------------------------------------------------ #
    # 5. Combine with original training data and save
    # ------------------------------------------------------------------ #
    original_df   = load_pairs(config["data"]["train_file"])
    synthetic_df  = pd.DataFrame(kept_pairs, columns=["mslg", "spa"])

    print(f"\nOriginal training pairs: {len(original_df)}")
    print(f"Synthetic pairs kept:    {len(synthetic_df)}")

    augmented_df = pd.concat([original_df, synthetic_df], ignore_index=True)
    print(f"Total augmented pairs:   {len(augmented_df)}")

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    augmented_df.to_csv(output_path, sep="\t", index=False)
    print(f"\nAugmented dataset saved to {output_path}")


if __name__ == "__main__":
    main()